{
 "title": "SSO Loadtest Board",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Project",
    "query": "label_values(keycloak_logins{instance=~\"$sso_instance\",job=\"sso\",provider=\"keycloak\"},namespace)"
   },
   {
    "name": "sso_instance",
    "label": "SSO Instance",
    "query": "label_values(keycloak_logins,instance)"
   },
   {
    "name": "sso_realm",
    "label": "Realm",
    "query": "label_values(keycloak_logins{instance=~\"$sso_instance\",job=\"sso\",provider=\"keycloak\"},realm)"
   },
   {
    "name": "sso_client_id",
    "label": "ClientId",
    "query": "label_values(keycloak_logins{instance=~\"$sso_instance\",job=\"sso\",provider=\"keycloak\",realm=~\"$sso_realm\"},client_id)"
   },
   {
    "name": "sp_instance",
    "label": "SP Instance",
    "query": "label_values(application_com_redhat_sso_SamlTestResource_test_saml_authn_count_total,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Users @ SP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(application_com_redhat_sso_TestDataResource_test_data_user_count{instance=~\"$sp_instance\"})"
    }
   ]
  },
  {
   "title": "SSO CPU Limit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{pod=~'sso-[0-9]+-.*',namespace='$namespace'})"
    }
   ]
  },
  {
   "title": "SSO CPU Usage Seconds",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container='sso'})"
    }
   ]
  },
  {
   "title": "RHSSO Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "application_com_redhat_sso_TestDataResource_test_data_sso_version"
    }
   ]
  },
  {
   "title": "SP Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "application_com_redhat_sso_TestDataResource_app_version"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 0 },
   "content": "\n# Red Hat SSO Loadtesting Board\n\nby Red Hat DACH Solution Architects\n\nFor more projects please refer to: [Git Repo](https://github.com/orgs/sa-mw-dach/teams/sa-mw-dach)\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "content": "<img src=\"https://static.redhat.com/libs/redhat/brand-assets/2/corp/logo--200.png\"/>"
  },
  {
   "title": "Network Packages Transmitted",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{pod=~'fortio-.*',namespace='$namespace'}[1m]))",
     "legendFormat": "Fortio"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{pod=~'sso-loadtest-sp-.*',namespace='$namespace'}[1m]))",
     "legendFormat": "SP"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{pod=~'sso-[0-9]+-.*',namespace='$namespace'}[1m]))",
     "legendFormat": "SSO"
    }
   ]
  },
  {
   "title": "Logins per CLIENT on realm $sso_realm",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(keycloak_logins{client_id=~\"$sso_client_id\",instance=~\"$sso_instance\",job=\"sso\",realm=~\"$sso_realm\",provider=\"keycloak\",namespace='$namespace'}[1m]))",
     "legendFormat": "SSO"
    },
    {
     "expr": "sum(rate(application_com_redhat_sso_SamlTestResource_test_saml_authn_login_sucess_count{instance=~\"${sp_instance}\",namespace='$namespace'}[1m]))",
     "legendFormat": "SP SAML"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pod:container_memory_usage_bytes:sum{pod=~'fortio-.*',namespace='$namespace'}",
     "legendFormat": "Fortio"
    },
    {
     "expr": "pod:container_memory_usage_bytes:sum{pod=~'sso-loadtest-sp-.*',namespace='$namespace'}",
     "legendFormat": "SP"
    },
    {
     "expr": "pod:container_memory_usage_bytes:sum{pod=~'sso-[0-9]+-.*',namespace='$namespace'}",
     "legendFormat": "SSO"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor_cpu_systemCpuLoad_percent",
     "legendFormat": "SP (App)"
    },
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'fortio-.*',namespace='$namespace'}",
     "legendFormat": "Fortio"
    },
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'sso-loadtest-sp-.*',namespace='$namespace'}",
     "legendFormat": "SP"
    },
    {
     "expr": "sum(pod:container_cpu_usage:sum{pod=~'sso-[0-9]+-.*'})",
     "legendFormat": "SSO"
    }
   ]
  },
  {
   "title": "JVM Memory Usage @ SSO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{instance=~\"$sso_instance\",job=\"sso\",namespace='$namespace'})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=~\"$sso_instance\",job=\"sso\",namespace='$namespace'})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"$sso_instance\",job=\"sso\",namespace='$namespace'})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "JVM Memory Usage @ SP",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_memoryPool_usage_max_bytes{instance=~\"$sp_instance\",job=\"sso-loadtest-sp\",namespace='$namespace'}) + sum(base_memory_maxHeap_bytes{instance=~\"$sp_instance\",job=\"sso-loadtest-sp\",namespace='$namespace'})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(vendor_memory_committedNonHeap_bytes{instance=~\"$sp_instance\",job=\"sso-loadtest-sp\",namespace='$namespace'}) + sum(base_memory_committedHeap_bytes{instance=~\"$sp_instance\",job=\"sso-loadtest-sp\",namespace='$namespace'})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(vendor_memory_maxNonHeap_bytes{instance=~\"$sp_instance\",job=\"sso-loadtest-sp\",namespace='$namespace'}) + sum(base_memory_usedHeap_bytes{instance=~\"$sp_instance\",job=\"sso-loadtest-sp\",namespace='$namespace'})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "SAML Request Duration AVG",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "keycloak_request_duration_sum{endpoint=\"web\",instance=~\"${sso_instance}\",job=\"sso\",method=\"POST\",namespace='$namespace',route=\"/realms/loadtest/login-actions/authenticate\",service=\"sso\"}/keycloak_request_duration_count{endpoint=\"web\",job=\"sso\",method=\"POST\",instance=~\"${sso_instance}\",route=\"/realms/loadtest/login-actions/authenticate\",service=\"sso\",namespace='$namespace'}",
     "legendFormat": "SSO"
    },
    {
     "expr": "application_com_redhat_sso_SamlTestResource_test_saml_authn_time_mean_seconds{instance=~\"${sp_instance}\",namespace='$namespace'} * 1000",
     "legendFormat": "SP"
    }
   ]
  },
  {
   "title": "SAML Authentication Request Histogram @ SSO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(keycloak_request_duration_bucket{endpoint=\"web\",instance=~\"${sso_instance}\",job=\"sso\",le=\"50.0\",method=\"POST\",route=\"/realms/loadtest/login-actions/authenticate\",service=\"sso\"}[1h]))",
     "legendFormat": "<= 50ms"
    },
    {
     "expr": "avg(increase(keycloak_request_duration_bucket{endpoint=\"web\",instance=~\"${sso_instance}\",job=\"sso\",le=\"100.0\",method=\"POST\",route=\"/realms/loadtest/login-actions/authenticate\",service=\"sso\"}[1h]))",
     "legendFormat": "<= 100ms"
    },
    {
     "expr": "avg(increase(keycloak_request_duration_bucket{endpoint=\"web\",instance=~\"${sso_instance}\",job=\"sso\",le=\"250.0\",method=\"POST\",route=\"/realms/loadtest/login-actions/authenticate\",service=\"sso\"}[1h]))",
     "legendFormat": "<= 250ms"
    },
    {
     "expr": "avg(increase(keycloak_request_duration_bucket{endpoint=\"web\",instance=~\"${sso_instance}\",job=\"sso\",le=\"500.0\",method=\"POST\",route=\"/realms/loadtest/login-actions/authenticate\",service=\"sso\"}[1h]))",
     "legendFormat": "<= 500ms"
    },
    {
     "expr": "avg(increase(keycloak_request_duration_bucket{endpoint=\"web\",instance=~\"${sso_instance}\",job=\"sso\",le=\"1000.0\",method=\"POST\",route=\"/realms/loadtest/login-actions/authenticate\",service=\"sso\"}[1h]))",
     "legendFormat": "<= 1s"
    },
    {
     "expr": "avg(increase(keycloak_request_duration_bucket{endpoint=\"web\",instance=~\"${sso_instance}\",job=\"sso\",le=\"2000.0\",method=\"POST\",route=\"/realms/loadtest/login-actions/authenticate\",service=\"sso\",namespace='$namespace'}[1h]))",
     "legendFormat": "<= 2s"
    },
    {
     "expr": "avg(increase(keycloak_request_duration_bucket{endpoint=\"web\",instance=~\"${sso_instance}\",job=\"sso\",le=\"10000.0\",method=\"POST\",route=\"/realms/loadtest/login-actions/authenticate\",service=\"sso\",namespace='$namespace'}[1h]))",
     "legendFormat": "<= 10s"
    },
    {
     "expr": "avg(increase(keycloak_request_duration_bucket{endpoint=\"web\",instance=~\"${sso_instance}\",job=\"sso\",le=\"30000.0\",method=\"POST\",route=\"/realms/loadtest/login-actions/authenticate\",service=\"sso\",namespace='$namespace'}[1h]))",
     "legendFormat": "<= 30s"
    },
    {
     "expr": "increase(keycloak_request_duration_bucket{endpoint=\"web\",instance=~\"${sso_instance}\",job=\"sso\",le=\"+Inf\",method=\"POST\",route=\"/realms/loadtest/login-actions/authenticate\",service=\"sso\",namespace='$namespace'}[1h])",
     "legendFormat": "All"
    }
   ]
  }
 ]
}
{
 "title": "Red Hat SSO Metrics",
 "description": "Monitoring RHSSO metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(keycloak_logins,instance)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(keycloak_logins{instance=\"$instance\",job=\"sso\",provider=\"keycloak\"},realm)"
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": "label_values(keycloak_logins{instance=\"$instance\",job=\"sso\",provider=\"keycloak\",realm=\"$realm\"},client_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Memory HEAP",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"heap\"})\n"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"$instance\",job=\"sso\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"$instance\",job=\"sso\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\",job=\"sso\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Logins Per REALM",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_logins{instance=\"$instance\"}) by (realm)",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Logins Per CLIENT",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_logins{instance=\"$instance\"}) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registrations Per CLIENT",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_registrations{instance=\"$instance\"}) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Logins per REALM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (realm)(increase(keycloak_logins{instance=\"$instance\",job=\"sso\"}[1h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Login Errors on realm $realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_failed_login_attempts{instance=\"$instance\",job=\"sso\",provider=\"keycloak\",realm=\"$realm\"}[1h])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Logins per CLIENT on realm $realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_logins{instance=\"$instance\",job=\"sso\",realm=\"$realm\",provider=\"keycloak\"}[1h])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Login Errors for $ClientId",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_failed_login_attempts{instance=\"$instance\",job=\"sso\",provider=\"keycloak\",realm=\"$realm\",client_id=\"$ClientId\"}[1h])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Registrations per CLIENT on relm $realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_registrations{instance=\"$instance\",job=\"sso\",realm=\"$realm\",provider=\"keycloak\"}[1h])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registration Errors for $ClientId",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_registrations_errors{instance=\"$instance\",job=\"sso\",provider=\"keycloak\",realm=\"$realm\",client_id=\"$ClientId\"}[1h])",
     "legendFormat": "{{error}}"
    }
   ]
  }
 ]
}